"""Generate supabase/migrations/0003_seed.sql from lib/data/sample_data.dart.

Keeping the seed generated from the Dart source means the bundled sample data
and the database cannot drift apart by hand. Re-run after editing the sample
data:  python3 tool/gen_seed.py
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = (ROOT / 'lib/data/sample_data.dart').read_text()


def literals(text, key, start=0):
    """Collect adjacent Dart string literals after `key` ('a ' 'b' -> 'a b')."""
    i = text.find(key, start)
    if i < 0:
        return ''
    i += len(key)
    parts = []
    while True:
        while i < len(text) and text[i] in ' \t\r\n,':
            i += 1
        if i < len(text) and text[i] == "'":
            j, buf = i + 1, []
            while j < len(text) and text[j] != "'":
                if text[j] == '\\':
                    j += 1
                buf.append(text[j])
                j += 1
            parts.append(''.join(buf))
            i = j + 1
        else:
            break
    return ' '.join(''.join(parts).split())


def num(text, key):
    m = re.search(rf"{key}:\s*(-?[\d.]+)", text)
    return float(m.group(1)) if m else 0.0


def esc(s):
    return s.replace("'", "''")


rows = []
for m in re.finditer(r'Place\((.*?)\n    \),', src, re.S):
    b = m.group(1)
    rows.append(dict(
        id=re.search(r"id:\s*'([^']*)'", b).group(1),
        name=literals(b, 'name:'),
        cat=re.search(r'category:\s*PlaceCategory\.(\w+)', b).group(1),
        lat=num(b, 'latitude'), lng=num(b, 'longitude'),
        rat=num(b, 'rating'), rc=int(num(b, 'reviewCount')),
        st=re.search(r'openStatus:\s*OpenStatus\.(\w+)', b).group(1),
        close=literals(b, 'closingTime:'),
        desc=literals(b, 'description:'),
        addr=literals(b, 'address:'),
    ))

out = ["""-- RevMap: seed data.  GENERATED by tool/gen_seed.py -- do not hand-edit.
--
-- One city plus the same places the app bundles in lib/data/sample_data.dart,
-- so the map has real data the moment it connects. Because this file is
-- generated from that Dart source, the sample data and the database cannot
-- drift apart by hand.
--
-- Re-runnable: ids are derived with md5(...) so they are stable, and every
-- insert is an upsert. Re-running after editing the sample data is safe.
--
-- Coordinates are two ordinary columns; the composite index on
-- (latitude, longitude) serves the map's viewport query.

insert into cities (name, country, centre_lat, centre_lng)
values ('Bengaluru', 'India', 12.9716, 77.5946)
on conflict (name, country) do nothing;
"""]

for r in rows:
    # places.id is uuid, so derive a deterministic one from the sample id.
    uid = f"md5('revamp:{r['id']}')::uuid"
    out.append(f"""
insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values ({uid},
        (select id from cities where name = 'Bengaluru' limit 1),
        '{esc(r['name'])}', '{r['cat']}', '{esc(r['desc'])}', '{esc(r['addr'])}',
        {r['lat']}, {r['lng']}, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;""")

out.append("""

-- Rating and review count are display aggregates, not reviews. Once real
-- reviews exist these come from place_rating() / place_confidence() instead.
-- Kept as a separate seeded aggregate rather than fabricated review rows,
-- because a fake review would be indistinguishable from a real one once trust
-- scoring applies -- which is exactly the failure this system exists to prevent.
create table if not exists place_seed_stats (
  place_id     uuid primary key references places(id) on delete cascade,
  rating       numeric(2,1) not null,
  review_count integer not null,
  open_status  text not null default 'open',
  closing_time text
);""")

for r in rows:
    uid = f"md5('revamp:{r['id']}')::uuid"
    ct = 'NULL' if not r['close'] else "'" + r['close'] + "'"
    out.append(f"""
insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values ({uid}, {r['rat']}, {r['rc']}, '{r['st']}', {ct})
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;""")

(ROOT / 'supabase/migrations/0003_seed.sql').write_text('\n'.join(out) + '\n')
print(f"wrote 0003_seed.sql with {len(rows)} places")
