-- RevMap: seed data.  GENERATED by tool/gen_seed.py -- do not hand-edit.
--
-- One city plus the same places the app bundles in lib/data/sample_data.dart,
-- so the map has real data the moment it connects. Because this file is
-- generated from that Dart source, the sample data and the database cannot
-- drift apart by hand.
--
-- Re-runnable: ids are derived with md5(...) so they are stable, and every
-- insert is an upsert. Re-running after editing the sample data is safe.
--
-- Coordinates are two ordinary columns; the composite index on
-- (latitude, longitude) serves the map's viewport query.

insert into cities (name, country, centre_lat, centre_lng)
values ('Bengaluru', 'India', 12.9716, 77.5946)
on conflict (name, country) do nothing;


insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p1')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Cubbon Park', 'attraction', 'One of the largest green spaces in the city, with walking paths, lakes and the Cubbon Park metro stop at the west gate.', 'Sampangi Rama Nagar',
        12.9763, 77.5929, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p2')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Third Wave Coffee', 'coffee', 'Specialty coffee on Church Street, a short walk from the metro.', 'Church Street',
        12.9695, 77.5963, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p3')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Chinnaswamy Stadium', 'attraction', 'Test cricket ground in the heart of the city.', 'MG Road',
        12.9788, 77.5996, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p4')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'The Lalit Ashok', 'hotel', 'Long-standing luxury hotel with a large garden.', 'Kempapura',
        12.9661, 77.6003, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p5')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Indian Museum', 'museum', 'One of the oldest museums in India.', 'Jawaharlal Nehru Road',
        12.9726, 77.5712, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p6')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'UB City', 'shopping', 'Mixed-use complex with shops, offices and a food court.', 'Vittal Mallya Road',
        12.9718, 77.5958, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p7')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Toit', 'restaurant', 'Brewery and kitchen, busy from evening onwards.', '100 Feet Road',
        12.9708, 77.6093, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p8')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Lalbagh Botanical Garden', 'park', 'A large botanical garden with a glasshouse.', 'Mavalli',
        12.9507, 77.5848, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p9')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Gangubai Kaum', 'hotel', 'Budget stay near the commercial district.', 'VV Puram',
        12.9654, 77.6182, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p10')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Koshy’s', 'restaurant', 'Long-running bakery and restaurant chain.', 'Sampangi Rama Nagar',
        12.9754, 77.6062, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p11')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'National Gallery of Modern Art', 'museum', 'Modern and contemporary Indian art in a park setting.', 'M.G. Road',
        12.9719, 77.6094, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;

insert into places (id, city_id, name, category, description, address_text,
                    latitude, longitude, status)
values (md5('revamp:p12')::uuid,
        (select id from cities where name = 'Bengaluru' limit 1),
        'Garuda Mall', 'shopping', 'Neighbourhood shopping mall with a cinema.', 'Magrath Road',
        12.9667, 77.6071, 'published')
on conflict (id) do update set
  name = excluded.name, category = excluded.category,
  description = excluded.description, address_text = excluded.address_text,
  latitude = excluded.latitude, longitude = excluded.longitude,
  status = excluded.status;


-- Rating and review count are display aggregates, not reviews. Once real
-- reviews exist these come from place_rating() / place_confidence() instead.
-- Kept as a separate seeded aggregate rather than fabricated review rows,
-- because a fake review would be indistinguishable from a real one once trust
-- scoring applies -- which is exactly the failure this system exists to prevent.
create table if not exists place_seed_stats (
  place_id     uuid primary key references places(id) on delete cascade,
  rating       numeric(2,1) not null,
  review_count integer not null,
  open_status  text not null default 'open',
  closing_time text
);

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p1')::uuid, 4.6, 8420, 'open', '20:00')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p2')::uuid, 4.4, 3180, 'open', '23:00')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p3')::uuid, 4.5, 12900, 'closed', NULL)
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p4')::uuid, 4.3, 2140, 'open', NULL)
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p5')::uuid, 4.4, 5680, 'closingSoon', '18:30')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p6')::uuid, 4.5, 9760, 'open', '22:00')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p7')::uuid, 4.2, 6320, 'open', '01:00')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p8')::uuid, 4.7, 15200, 'open', '18:00')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p9')::uuid, 4.1, 890, 'closed', NULL)
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p10')::uuid, 4.4, 4410, 'open', '22:30')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p11')::uuid, 4.2, 1870, 'closed', NULL)
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;

insert into place_seed_stats (place_id, rating, review_count, open_status, closing_time)
values (md5('revamp:p12')::uuid, 4.0, 3320, 'open', '22:00')
on conflict (place_id) do update set
  rating = excluded.rating, review_count = excluded.review_count,
  open_status = excluded.open_status, closing_time = excluded.closing_time;
